//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_tipo_solicitud
    {
        public int_tipo_solicitud()
        {
            this.int_responsables = new HashSet<int_responsables>();
            this.int_solicitudes = new HashSet<int_solicitudes>();
        }
    
        public int tip_sol_id { get; set; }
        public string tip_sol_nombre { get; set; }
    
        public virtual ICollection<int_responsables> int_responsables { get; set; }
        public virtual ICollection<int_solicitudes> int_solicitudes { get; set; }
    }
}
