//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_responsables
    {
        public int_responsables()
        {
            this.int_solicitudes = new HashSet<int_solicitudes>();
        }
    
        public int res_id { get; set; }
        public string res_nombre { get; set; }
        public string res_apellido { get; set; }
        public string res_correo { get; set; }
        public Nullable<int> res_anexo { get; set; }
        public Nullable<int> res_tip_sol_id { get; set; }
    
        public virtual int_tipo_solicitud int_tipo_solicitud { get; set; }
        public virtual ICollection<int_solicitudes> int_solicitudes { get; set; }
    }
}
