//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_empresas
    {
        public int_empresas()
        {
            this.int_sucursales = new HashSet<int_sucursales>();
        }
    
        public int emp_id { get; set; }
        public string emp_nombre { get; set; }
        public string emp_rut { get; set; }
        public Nullable<System.DateTime> emp_feccre { get; set; }
        public Nullable<int> emp_usucre { get; set; }
    
        public virtual ICollection<int_sucursales> int_sucursales { get; set; }
    }
}
