//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_com_historial
    {
        public int com_his_id { get; set; }
        public Nullable<int> com_his_eve_com_id { get; set; }
        public string com_his_eve_com_cuerpo { get; set; }
        public Nullable<System.DateTime> com_his_eve_com_feccre { get; set; }
    
        public virtual int_eve_comentarios int_eve_comentarios { get; set; }
    }
}
