//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_eve_detalle
    {
        public int eve_det_id { get; set; }
        public Nullable<int> eve_det_eve_id { get; set; }
        public string eve_det_imagen { get; set; }
        public Nullable<System.DateTime> eve_det_feccre { get; set; }
        public Nullable<System.DateTime> eve_det_fecmod { get; set; }
        public Nullable<int> eve_det_usucre { get; set; }
    
        public virtual int_eventos int_eventos { get; set; }
    }
}
