//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_eve_comentarios
    {
        public int_eve_comentarios()
        {
            this.int_com_historial = new HashSet<int_com_historial>();
        }
    
        public int eve_com_id { get; set; }
        public string eve_com_cuerpo { get; set; }
        public Nullable<int> eve_com_usu_id { get; set; }
        public Nullable<int> eve_com_eve_id { get; set; }
        public Nullable<System.DateTime> eve_com_feccre { get; set; }
        public Nullable<System.DateTime> eve_com_fecmod { get; set; }
    
        public virtual ICollection<int_com_historial> int_com_historial { get; set; }
        public virtual int_eventos int_eventos { get; set; }
        public virtual int_usuarios int_usuarios { get; set; }
    }
}
