//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_directorios
    {
        public int dir_id { get; set; }
        public Nullable<int> dir_anexo { get; set; }
        public Nullable<int> dir_movil { get; set; }
        public Nullable<int> dir_usu_id { get; set; }
        public Nullable<int> dir_suc_id { get; set; }
        public Nullable<System.DateTime> dir_feccre { get; set; }
        public Nullable<int> dir_usucre { get; set; }
    
        public virtual int_sucursales int_sucursales { get; set; }
        public virtual int_usuarios int_usuarios { get; set; }
    }
}
