//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_solicitudes
    {
        public int sol_id { get; set; }
        public string sol_titulo { get; set; }
        public string sol_cuerpo { get; set; }
        public Nullable<System.DateTime> sol_feccre { get; set; }
        public Nullable<int> sol_res_id { get; set; }
        public Nullable<int> sol_tip_sol_id { get; set; }
        public Nullable<int> sol_usu_id { get; set; }
    
        public virtual int_responsables int_responsables { get; set; }
        public virtual int_tipo_solicitud int_tipo_solicitud { get; set; }
        public virtual int_usuarios int_usuarios { get; set; }
    }
}
