//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_eventos
    {
        public int_eventos()
        {
            this.int_eve_comentarios = new HashSet<int_eve_comentarios>();
            this.int_eve_detalle = new HashSet<int_eve_detalle>();
        }
    
        public int eve_id { get; set; }
        public string eve_nombre { get; set; }
        public string eve_motivo { get; set; }
        public Nullable<System.DateTime> eve_feccre { get; set; }
        public Nullable<System.DateTime> eve_fecmod { get; set; }
        public Nullable<int> eve_usucre { get; set; }
        public Nullable<System.DateTime> eve_fec_realizacion { get; set; }
        public Nullable<int> eve_usu_id { get; set; }
    
        public virtual ICollection<int_eve_comentarios> int_eve_comentarios { get; set; }
        public virtual ICollection<int_eve_detalle> int_eve_detalle { get; set; }
        public virtual int_usuarios int_usuarios { get; set; }
    }
}
